### ISSUE TITLE
Problems with Party and "Complete mission within"

### ISSUE THREAD

**Issue by Lokarda2** [ezeiger92/QuestWorld2#102]
Hi, there is a problem with the party system. I am unable to invite anyone. It gives out a message saying that he already has a party even though he/she doesnt.

There also is a problem with "comlpete mission within" option as it keeps spamming the failiure message. Rendering this option useless. Tho it works with ChatReaction. I have tested it with Votes and Fishing and with these two it doesnt work. With ChatReaction it does.

**Comment by Lokarda2** [comment]
Also once you complete redoable quest it assigns it the "COMPLETED" mark and after cooldown the mark never gets deleted it stays forever. You end up being able to do the quest but it is still marked as COMPLETED

**Comment by ezeiger92** [comment]
With parties, your players likely have `party.associated` set in their progress file despite not being in that party. I don't believe that is possible with the current code, it might be the result of a previous version. What version are you currently using, and what version (if any) did you last update from?

I'll take another look at timeframes, their logic was completely backwards and I probably forgot to switch a thing.

Quests keeping the "COMPLETED" text is old behavior and intentional. It doesn't reflect the quest state as being completed, but rather that the quest has been completed at some point.

**Comment by Lokarda2** [comment]
QuestWorld 2.6.10

This is the first version of QuestWorld for us. Installed like few days back.

**Comment by ezeiger92** [comment]
Invites are only sent once, if the player doesn't accept they will be stuck in the pending list, which may be what's happening to you. I consider this a bug. The timeframe issue was fixed on the snapshot branch before this ticket (surprised myself there), and I'll try to make a build soon to fix these.
