### ISSUE TITLE
MythicMobs Support

### ISSUE THREAD

**Issue by Worlfy** [ezeiger92/QuestWorld2#130]
Hi,

Besides having the "Kill named mob", why can't we have a "Kill MythicMobs Mob"?
This'll take in the internal mob-name rather than having to type over the mob-name and make sure they're all unique and don't have the same as another mob, or else the quest will accept both, which is not what I, and I think many other MM users want.

Kind regards,
zThana

**Comment by UltraFaceguy** [comment]
While I think that support for MM should probably have that, I am curious - why the heck do you have non mythic monsters with the exact same names as mythic monsters? How did that come to pass? 🤔

**Comment by UltraFaceguy** [comment]
Ah, so it's more of you want monsters with different names to count towards the same objective, as they're different level varients of the base monster. Though I don't exactly understand the boss and minion example. Wouldn't they have different names?

**Comment by Worlfy** [comment]
Wouldn't always have to be that way

But yes I do get your point. Just thought it'd be a bit better, so we don't always have to change the quest upon renaming a mob

**Comment by Zicerite** [comment]
The main reason why i requested a "Kill named mob" with a "contains" thing on it a long time ago, is so that you can check for a mythic mob with a name.

You simply put in the mob's name, and enable "Contains".

It ignores the other stuff in the mob's name, like the level text and symbols you might put in it.

![2018-08-15_07 34 17](https://user-images.githubusercontent.com/30883277/44153697-cc10f522-a05d-11e8-8646-6701b4e8fabe.png)
![2018-08-15_07 35 06](https://user-images.githubusercontent.com/30883277/44153699-cc266376-a05d-11e8-8452-d3b13f20c884.png)

**Comment by Worlfy** [comment]
Read my comment above

**Comment by Zicerite** [comment]
In my opinion, It would just be better to name the minions differently anyway. That's what I do.
Besides, you'd make the mobs first, before making the quest anyway. 
It is better to stick with a name, than keep changing it.

**Comment by Blackyvk** [comment]
what happens if a player renames a mob as a mythicmobs mob ? does it counts for the quest ?

**Comment by ezeiger92** [comment]
It does. For most servers, you can use color codes in the mob name as a workaround, as players can't normally change text colors.
