### ISSUE TITLE
Could you add support for 1.9.4

### ISSUE THREAD

**Issue by alexdemond** [ezeiger92/QuestWorld2#143]
I really like the plugin, but seemed that the plugin doesn't support 1.9.4 even if I drop Legacy.jar into the folder, I'm wondering whether you would like to support it.

**Comment by ezeiger92** [comment]
The legacy extention was a proof of concept that was supposed to help with the 1.12/1.13 gap. Things did not go that way.

If you post stacktraces and they are caused by errors in plugin logic, I’ll fix them. In general I don’t support any version other than 1.12.2 and 1.13.x (though there’s no release for 1.13 yet)

**Comment by ezeiger92** [comment]
If I don't know what the specific issue is, I have no way to consider fixing it.

**Comment by alexdemond** [comment]
Ops sorry for my late reply because I have to go to school.  I will send you my log when I get home at Friday.

**Comment by alexdemond** [comment]
https://pastebin.com/htkTzXZF
I get this when I click the quest，then it says 'An internal error...'

**Comment by ezeiger92** [comment]
The latest build of QuestWorld + QW-Legacy should be reasonably stable on 1.9.4,  though that QuestWorld itself is in alpha.
