### ISSUE TITLE
1.16 Support

### ISSUE THREAD

**Issue by doitliketyler** [ezeiger92/QuestWorld2#165]
Any chance of adding support for 1.16+ servers? Currently the plugin will load but nothing is usable in game.

**Comment by ezeiger92** [comment]
My server is using 2.8.0-RC1 [(link)](https://github.com/ezeiger92/QuestWorld2/releases/tag/v2.8.0-RC1) on 1.16.3 right now without issue, see if that works for you. If not, send me a log file and I can sort out what's going wrong.

Fair warning: If you are using the citizens extension, that is probably broken too. I don't personally use it so I don't notice when things stop working with it, and I know Citizens had a decent amount of code change at some point.

**Comment by tylerking** [comment]
Originally the plugin would load but I could open the quest gui at all but I tried re-installing based on your suggestion and everything so far is working fine and I haven't been able to reproduce the issue. I do have the Citizens extension installed too so that's good. Guess I'll report back if something else arises. Thank you.
