### ISSUE TITLE
Feature: Anti grinder on mob kills

### ISSUE THREAD

**Issue by erik1988** [ezeiger92/QuestWorld2#18]
It would be great if you could add an antigirnder feature to mob kills.
E.g. you cannot kill mobs in water or mobs that cannot reach you.
The anti grinder in extra hard mode works really well:
https://github.com/MLG-Fortress/ExtraHardMode/blob/master/src/main/java/com/extrahardmode/features/AntiGrinder.java

**Comment by ezeiger92** [comment]
The current plan (no idea how long it will take) is to switch a bunch of things over to events. With that, people can cancel events they don't want to occur. I don't really want to put anti-grinder code in because it tends to have false positives, and I think server owners should be the ones deciding how to balance false positives/false negatives.

Looking through that code in particular, I can see legitimate kills that will be cancelled and grinder style kills that are allowed. That code may work well enough for you, but I use a completely different system on my server because of how we've set things up.

**Comment by erik1988** [comment]
A config option to toggle some kind of anti-grinder would be great! It could be less aggressive than the one I provided, but at least something would be nice.

Im curious, what specific things are problematic with the code I linked to? I have been using this for months to clear drops and my players have still not been able to make grinders that works. If there is a way to work around this I would like to know about that before my players does :).

I tell them that they should not kill monsters in water and that the monsters needs to be able to reach you. 

Thanks!

**Comment by ezeiger92** [comment]
I could be wrong on any of these, but here's what I see at a glance:
- On mob kill, normal skeletons are treated as wither skeletons, making none of the water checks happen. Likewise, wither skeletons are treated as normal skeletons
- Enderman can be safely killed in the end by standing under a few blocks and looking around to get agro
- Wither boss and guardian grinders work as long as the player manually kills the mob
- When calculating adjacent blocks, the second loop should have [i + 1 + adjacentFaces.length], otherwise the last block on eye level is overwritten and the very last block never gets filled
- The location checks can allow bow kills on trapped mobs if they are pushed against the wall closest to the player and the player is at least 5 blocks away
- The location check can deny kills when the mob is around a corner or on the other side of a tree, which they can easily walk around to reach the player
- Spawning code prevents dragons from spawning ever
- Spawning code allows mob-proof areas by placing a bunch of non-natural blocks

Some of these are likely accounted for in other parts of that plugin, but I wouldn't trust it as a stand-alone anti-grinder

**Comment by erik1988** [comment]
Thanks ezeiger92, as you can see I have made a post about it on the plugin. 

I can definitely confirm the enderman thing. But im pretty sure that skeletons does not drop loot in water. 
Also the dragon spawns without any issues.  As for the other things I am not sure. 
Again thanks for your feedback. :)

If you have a solution to any of these, i'm sure the author would appreciate a pull request that improve the process.

**Comment by ezeiger92** [comment]
I'm going to close this one. It's something that can easily be handled by other plugins, and I don't want QuestWorld to suffer from feature creep. Also all of the stuff I said above.
