### ISSUE TITLE
"Travel to" radius has become 0

### ISSUE THREAD

**Issue by erik1988** [ezeiger92/QuestWorld2#35]
Looks like the radius on the travel to quest has become 0 instead of the default 1. Seems like the one that was already set still has their number.

When that is said it would be nice to have a config option to set the default radius, or perhaps always make it 2? I get many complains that they dont work because they are not directly on top of the block.

**Comment by ezeiger92** [comment]
For clarity, the issue is just that the default radius is now 0?
Old quests work fine and changing the radius works fine? I changed a fair bit with location quests, just wanted to make sure.

A config option for default radius... that would be like an option for default kill amount. I'm not sure it's that useful. If it's something you really think is needed, make a new issue for it. I've been really busy and am likely to lose track otherwise :P

**Comment by erik1988** [comment]
yes you are correct. 
the default radius is now 0 and it affect old quests that did not have the radius set. 
I noticed this since some old location quests that used to work before, did not work anymore. 
So when I checked the radius it said 0 and it was the same for any other quest that the radius was not already set. 

It would be helpful if the one that now says 0 is changed to 1 again automatically since we have over 200 quests :S. Or that the system would always read 0 as 1.

**Comment by ezeiger92** [comment]
... Every quest has a radius set. If quests that used to have a radius now have 0, that is a more serious bug.

**Comment by ezeiger92** [comment]
Radius < 1 was never valid, just put a check on the updater to change it to 1, should fix this. No push yet because I've got too much stuff going on. Will close when I push the fix.

**Comment by erik1988** [comment]
Thank you. You are awesome!
