### ISSUE TITLE
Using Citizens Submit with Sentinel doesn't work

### ISSUE THREAD

**Issue by silverforte** [ezeiger92/QuestWorld2#5]
Trying to give an item to an NPC using Sentinel (Citizens Submit) doesn't work. Nothing happens, no errors. Server must be restarted for it to work after making a new NPC.

**Comment by ezeiger92** [comment]
So if you create an NPC and restart, you are able to complete the quest just fine?

I haven't messed with citizens before (or questworld's interaction with citizens), but I'll take a look when I get some time. Might need to catch an "npc create" event.

**Comment by ezeiger92** [comment]
Either I fixed this by accident, the mix of Citizens/Sentinel/Spigot/QuestWorld all having updates fixed this, or there was some configuration issue on your end way back in the day.

At any rate, cannot currently reproduce. I don't know if you are even around at this point because I took way too long to check this out. Over 8 months after the fact.... Sorry!

If you are still around and this issue is still a problem for you, let me know.
