### ISSUE TITLE
Could not pass event InventoryClickEvent to CS-CoreLib

### ISSUE THREAD

**Issue by wedza** [ezeiger92/QuestWorld2#50]
Hey

First, I really wanted to thank you for all your involvement and work to this plugin. Your support of QuestWorld really helps us to add life to our server and tell stories to our players, which we cannot have done with other complex plugins.

We have a little issue (I'm not a plugin developer but it seems to be from the connexion between CS Core Lib and QW2). And regularly, when we try to navigate in the GUI, we have an InventoryClickEvent which completely freezes some parts of the GUI (like [showed here](https://gyazo.com/5662c451361d55928d7cfb3ab323eb17)). Does QuestWorld2 compatible with CS Core Lib v1.5.16? Do we need to downgrade CS? (here is [a log](https://pastebin.com/FdFSDcXX) if you want to check it out)

And again, thanks for your amazing work, really.

**Comment by ezeiger92** [comment]
It looks like one of your missions did not save correctly (probably a different bug).

If you look in the plugins/QuestWorld/quests folder, one of your quests (like 0-C0.quest) will have an item with material "AIR". Changing it to "STONE" should let you edit it later.
Notepad++ lets you open many files and search in all open files, other editors do similar things. If you have one of those you should just need to search "AIR"

Let me know if that works for you or if you run into any trouble!


I'll put in code to prevent this in the future, but I've got a bunch of untested stuff in the pipeline, so that will take a while.

**Comment by wedza** [comment]
Wow ! Thanks for your fast reply!

Sadly, replacing air with another item didn't change anything, but I found that the right click was working, so deleting the task and create them again worked for me.

I think this happens because I was discovering the plugin with friends and we were working with the GUI together, so now we know. 😋 

Thanks !

**Comment by ezeiger92** [comment]
What, hold up, there's an actual issue here that I still need to fix in code! Lol
