### ISSUE TITLE
Extensions/CS-Corelib Error

### ISSUE THREAD

**Issue by doitliketyler** [ezeiger92/QuestWorld2#64]
Extensions don't seem to be working and the options are definitely not showing up in the quest editor. I'm getting this error in console on startup:

https://pastebin.com/A857m0in

Currently running on Paper Spigot 1.12.2...thoughts?

**Comment by ezeiger92** [comment]
You get that error when you use older versions of extensions, grab the ones from the [latest release page](https://github.com/ezeiger92/QuestWorld2/releases).
I didn't explicitly say it, but since I'm still heavily messing with the API, old extensions will not work. General rule: If I post new extension versions alongside a QuestWorld version, you probably have to use those extensions lol

I'm closing this ticket as "invalid", but if you have other issues with the up-to-date extensions let me know!

**Comment by doitliketyler** [comment]
Oops. That was my problem. Cheers!
